import dictionary from "./dictionary.js";

const toolsList = [
    {
        id: "screen-reader",
        icon: "ScreenReaderIcon",
        text: "tools.screenReader",
        options: [false, true],
        defaultValue: false,
        currentValue: false,
    },
    {
        id: "cursor",
        icon: "CursorIcon",
        text: "tools.cursor",
        options: ["auto", "white", "black", "mask", "readGuide"],
        defaultValue: "auto",
        currentValue: "auto",
    },
    {
        id: "text-size",
        icon: "FontSizeIcon",
        text: "tools.fontSize",
        options: ["small", "normal", "large", "extralarge", "giant"],
        defaultValue: "normal",
        currentValue: "normal",
    },
    {
        id: "text-font",
        icon: "FontFamilyIcon",
        text: "tools.fontFamily",
        options: ["current", "font-sans", "font-serif", "font-mono"],
        defaultValue: "current",
        currentValue: "current",
    },
    {
        id: "text-line-height",
        icon: "LineHeightIcon",
        text: "tools.lineHeight",
        options: ["normal", "loose", "extraloose"],
        defaultValue: "normal",
        currentValue: "normal",
    },
    {
        id: "text-spacing",
        icon: "LetterSpacingIcon",
        text: "tools.letterSpacing",
        options: ["normal", "loose", "extraloose"],
        defaultValue: "normal",
        currentValue: "normal",
    },
    {
        id: "text-alignment",
        icon: "TextAlignIcon",
        text: "tools.textAlign",
        options: ["auto", "left", "center", "right", "justify"],
        defaultValue: "auto",
        currentValue: "auto",
    },
    {
        id: "contrast",
        icon: "ContrastIcon",
        text: "tools.contrast",
        options: ["low", "normal", "high", "ultra", "inverted"],
        defaultValue: "normal",
        currentValue: "normal",
    },
    {
        id: "color-saturation",
        icon: "ColorSaturationIcon",
        text: "tools.colorSaturation",
        options: ["low", "normal", "high", "ultra"],
        defaultValue: "normal",
        currentValue: "normal",
    },
    {
        id: "hide-images",
        icon: "HideImagesIcon",
        text: "tools.hideImages",
        options: [false, true],
        defaultValue: false,
        currentValue: false,
    },
    {
        id: "highlighted-links",
        icon: "HighlightLinksIcon",
        text: "tools.highlightedLinks",
        options: [false, true],
        defaultValue: false,
        currentValue: false,
    },
    {
        id: "widget-size",
        icon: "WidgetSizeIcon",
        text: "tools.widgetSize",
        options: ["small", "medium", "large"],
        defaultValue: "medium",
        currentValue: "medium",
    },
    {
        id: "widget-position",
        icon: "WidgetPositionIcon",
        text: "tools.widgetPosition",
        options: ["left", "right"],
        defaultValue: "left",
        currentValue: "left",
    },
];

const languagesList = [
    {
        key: "es",
        icon: "SpanishIcon",
        label: "Español",
        dictionary: dictionary.es,
    },
    {
        key: "en",
        icon: "EnglishIcon",
        label: "English",
        dictionary: dictionary.en,
    },
    {
        key: "fr",
        icon: "FrenchIcon",
        label: "Français",
        dictionary: dictionary.fr,
    },
    {
        key: "de",
        icon: "GermanIcon",
        label: "Deutsch",
        dictionary: dictionary.de,
    },
    {
        key: "it",
        icon: "ItalianIcon",
        label: "Italiano",
        dictionary: dictionary.it,
    },
    {
        key: "pt",
        icon: "PortugueseIcon",
        label: "Português",
        dictionary: dictionary.pt,
    },
    {
        key: "nl",
        icon: "DutchIcon",
        label: "Nederlands",
        dictionary: dictionary.nl,
    },
    {
        key: "pl",
        icon: "PolishIcon",
        label: "Polski",
        dictionary: dictionary.pl,
    },
    {
        key: "ru",
        icon: "RussianIcon",
        label: "Русский",
        dictionary: dictionary.ru,
    },
    {
        key: "zh",
        icon: "ChineseIcon",
        label: "中文",
        dictionary: dictionary.zh,
    },
];

const profilesList = [
    {
        key: "blind",
        icon: "BlindIcon",
        label: "profiles.blind",
        tools: {
            hideImages: true,
            screenReader: true,
            cursor: "auto",
            fontSize: "large",
        },
    },
    {
        key: "dyslexia",
        icon: "DyslexiaIcon",
        label: "profiles.dyslexia",
        tools: {
            screenReader: true,
            contrast: "low",
            colorSaturation: "low",
            fontSize: "extralarge",
            fontFamily: "font-mono",
            letterSpacing: "loose",
            lineHeight: "loose",
            widgetSize: "large",
        },
    },
];

export { toolsList, languagesList, profilesList };
